export const PRODUCT_VERIFY_REQUEST = "PRODUCT_VERIFY_REQUEST";
export const PRODUCT_VERIFY_SUCCESS = "PRODUCT_VERIFY_SUCCESS";
export const PRODUCT_VERIFY_FAIL = "PRODUCT_VERIFY_FAIL";
export const PRODUCT_VERIFY_RESET = "PRODUCT_VERIFY_RESET";

export const PRODUCT_FARM_SAVE_DETAIL = "PRODUCT_FARM_SAVE_DETAIL"
export const PRODUCT_FARM_SAVE_DETAIL_RESET = 'PRODUCT_FARM_SAVE_DETAIL_RESET';