export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOCATION_REQUEST = 'USER_LOCATION_REQUEST';
export const USER_LOCATION_SUCCESS = 'USER_LOCATION_SUCCESS';
export const USER_LOCATION_FAIL = 'USER_LOCATION_FAIL';

export const USER_ADDFARM_REQUEST = 'USER_ADDFARM_REQUEST';
export const USER_ADDFARM_SUCCESS = 'USER_ADDFARM_SUCCESS';
export const USER_ADDFARM_FAIL = 'USER_ADDFARM_FAIL';
export const USER_ADDFARM_RESET = 'USER_ADDFARM_RESET';

export const USER_ADDFARM_DETAILS_REQUEST = 'USER_ADDFARM_DETAILS_REQUEST';
export const USER_ADDFARM_DETAILS_SUCCESS = 'USER_ADDFARM_DETAILS_SUCCESS';
export const USER_ADDFARM_DETAILS_FAIL = 'USER_ADDFARM_DETAILS_FAIL';
export const USER_ADDFARM_DETAILS_RESET = 'USER_ADDFARM_DETAILS_RESET';

export const USER_FARMS_REQUEST = 'USER_FARMS_REQUEST';
export const USER_FARMS_SUCCESS = 'USER_FARMS_SUCCESS';
export const USER_FARMS_FAIL = 'USER_FARMS_FAIL';

export const USER_FARM_DETAIL_REQUEST = 'USER_FARM_DETAIL_REQUEST';
export const USER_FARM_DETAIL_SUCCESS = 'USER_FARM_DETAIL_SUCCESS';
export const USER_FARM_DETAIL_FAIL = 'USER_FARM_DETAIL_FAIL';

export const USER_HISTORY_REQUEST = "USER_HISTORY_REQUEST";
export const USER_HISTORY_SUCCESS = "USER_HISTORY_SUCCESS";
export const USER_HISTORY_FAIL = "USER_HISTORY_FAIL";

export const USER_LOGS_REQUEST = 'USER_LOGS_REQUEST';
export const USER_LOGS_SUCCESS = 'USER_LOGS_SUCCESS';
export const USER_LOGS_FAIL = 'USER_LOGS_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST';
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS';
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL';